neo4j-labs/neo4rs

- Cargo.toml
Hello @yehohanan7,
Having the `repository` key in your `Cargo.toml` helps people find this repo when seeing your crate on `docs.rs` or `crates.io`.
Keep up the good work! 😄
> Add `repository` to `Cargo.toml`

- lib/src/convert.rs
In its current state, neo4rs does not appear to support lists/vectors in node properties and probably elsewhere due to missing `Into` and `TryFrom` implementations. This patch firstly adds support for `Vec<A>` given `A` is already convertible to/from `BoltType`. Secondly, an implementation of `Into<BoltType> for f64` is provided, as this seems to be already supported the other way around.
These changes together should allow using neo4rs to work with databases containing vector embeddings. Edits by maintainers are on, so feel free to edit anything if it's not up to standard.
> Implement Into/TryFrom BoltType for Vec and Into for f64

- lib/src/config.rs
- lib/src/lib.rs
- lib/src/stream.rs
- lib/src/txn.rs
- Fully qualify links in docs
- Don't use deprecated methods in doc tests
> Eliminate warnings and deprecations from docs

- lib/src/lib.rs
- lib/src/messages/run.rs
According to the [specification](https://neo4j.com/docs/bolt/current/packstream/) a struct with 3 fields is supposed to have the marker `B3`.
The `Run` struct was marked with `B1` instead (struct with 1 field), which causes problems with Neo4j 5.2.
After changing it to `B3` all test run successfully with versions 4.4.18 and 5.2.0.
Additionally `distance` was renamed to `point.distance` in version 4.4 ([reference](https://neo4j.com/docs/cypher-manual/4.4/functions/spatial/)).
> Compatibility with Neo4j version 5 and 4.4.

- lib/Cargo.toml
- lib/src/errors.rs
This implements the error trait using `thiserror`.
In general, restructuring the Error type would probably a good idea (e.g. have type and marker as fields of `InvalidMarker` instead of a message string), but that would be a breaking change.
> Implement Error trait using thiserror.

- lib/src/query.rs
Here we can pass params as a standard hashmap.
Reason being it is tedious to keep calling param constantly for each new input. 
This will make it more pleasing to work with as a lot of people already have hashmaps in their projects.
> Pass multiple params as a hashmap

- Cargo.toml
- README.md
- ci/Cargo.lock.min
- ci/Cargo.lock.msrv
- lib/Cargo.toml
- lib/src/connection.rs
- lib/src/errors.rs
- lib/src/lib.rs
- lib/src/messages.rs
- lib/tests/container.rs
- rust-toolchain.toml
Only "proper" certificates are supported right now (i.e. `bolt+s` or `neo4j+s` schemes).
We use [`rustls`](https://lib.rs/crates/rustls) for the TLS implementation and load root certificates with [`webpki-roots`](https://lib.rs/crates/webpki-roots).
Self-signed certificates are not supported yet.
We plan to support self-signed certificates, as well as custom certificate chains und native TLS implementations in the future.
Only manually tested against Aura, no automated tests yet until we figure out how to create a testcontainer with an encrypted server setup.
Fixes #81
> Support encrypted connections

- lib/src/convert.rs
Query strings that use a placeholder `$foo` for an `Option<Into<BoltType>>` cannot be constructed without first knowing if the option is `None`. This is bothersome because basic query strings for a struct can be determined without `self`, but filling in query params requires a `self`.
This PR associates a query parameter  of  `None` to mean `BoltType::Null(BoltNull)`. 
Does this change semantics? Before this, removing a property on an entity could be done via `SET n.prop = null`, but now it could be done with `SET n.prop = $prop`. It allows a kind of silly Option<Vec<Option<A>>> as a type. 
Will `serde` support take care of this (there's a draft PR)?
> Implement From<Option> for BoltType

- lib/src/query.rs
This is to expose the ability to warn, etc. if overwriting an existing param key.
> add Query::has_param_key

- ci/Cargo.lock.min
- ci/Cargo.lock.msrv
- lib/Cargo.toml
- macros/Cargo.toml
- Update min versions cargo lock file
- Set MSRV to 1.63 for all crates and update lockfile accordingly
> Set MSRV to 1.63 for all crates

- .gitignore
- lib/Cargo.toml
- lib/include/streams_within_a_transaction.rs
- lib/src/errors.rs
- lib/src/row.rs
- lib/src/stream.rs
- lib/src/types/string.rs
- lib/tests/txn_change_db.rs
Adding a few methods to the RowStream that allow it to be treated as a
`futures::Stream`, optionally with serde integration.
Also, we try to parse a single column of a row if parsing the row as a whole fails.
> Improve API for RowStream

- lib/include/rollback_a_transaction.rs
- lib/include/streams_within_a_transaction.rs
- lib/include/transactions.rs
- lib/include/txn_vs_graph.rs
- lib/src/connection.rs
- lib/src/graph.rs
- lib/src/messages/commit.rs
- lib/src/messages/reset.rs
- lib/src/messages/rollback.rs
- lib/src/pool.rs
- lib/src/query.rs
- lib/src/stream.rs
- lib/src/txn.rs
- lib/tests/txn_change_db.rs
Connections are no longer always wrapped in an Arc<Mutex<>>.
This actually introduces a number of breaking changes:
- `Graph::execute` returns a `DetachedRowStream` instead of a `RowStream` (name pending)
The API is identical, but it's a different type
- `Txn::execute` continues to return a `RowStream`, but its API changed:
- `RowStream::next` required a `TransactionHandle`, which can be obtained by calling `Txn::handle`
- This method is defined as `fn handle(&mut self)`, which means that the synchronization of concurrent query streams within a single transactions must now be handled by the user
- The same is true for all other methods consuming the `RowStream`
- `Txn` methods now require `&mut self` instead of `&self`
> breaking! Remove internal mutex boxing of connections

- README.md
- lib/include/streams_within_a_transaction.rs
- lib/include/transactions.rs
- lib/src/query.rs
- lib/src/txn.rs
- lib/tests/txn_change_db.rs
Allows to use any `IntoIter` with any `Into<Query>`.
> Be more flexible in what is accepted for run_queries

- README.md
- lib/src/config.rs
- lib/src/graph.rs
- lib/src/lib.rs
- lib/src/txn.rs
- lib/tests/container.rs
- deadpool::Pool are "cheap to clone because of reference counting" according to their doc.
- We only store the config values we actually need after having created the pool and use `Arc<str>` for the string to also get a cheap clone
- Now we can make `Graph: Clone`
> Only store cheap/rc cloneable fields inside of Graph

- lib/src/types/serde/element.rs
- lib/src/types/serde/error.rs
- lib/src/types/serde/node.rs
- lib/tests/missing_properties.rs
> Deserialize missing properties as none

- lib/Cargo.toml
- lib/src/convert.rs
Implementing `TryInto` let's users do:
```rust
.param("inputs", neo4rs::BoltType::try_from(serde_json::to_value(some_serializable_value)?)?)
```
It would be nice to avoid explicitly calling `try_from` here, but `param` doesn't return a `Result` so... I don't want to introduce breaking changes
> Implement TryInto<serde_json::Value>, with optional `json` feature

- lib/src/connection.rs
The code was incorrect, and [it caused UB in the wild](https://stackoverflow.com/q/78776053/7884305), because `BytesMut::reserve()` reserves **len**+X, not **capacity**+X.
But even without that bug, this unsafe code was UB, since [treating uninitialized integers as initialized is UB](https://doc.rust-lang.org/stable/reference/behavior-considered-undefined.html).
Fortunately, the unsafe code can be eliminated completely, and yet without zeroing the array.
You may consider yanking the affected versions.
> Remove an unsafe block

- .github/workflows/checks.yml
- .github/workflows/create-release-pr.yml
- ci/Cargo.lock.min
- ci/Cargo.lock.msrv
- lib/Cargo.toml
- lib/examples/concurrent_writes.rs
- lib/src/errors.rs
- lib/src/graph.rs
- lib/src/lib.rs
- lib/src/messages.rs
- lib/src/pool.rs
- lib/src/query.rs
When using `Graph::run`, `Graph::run_on`, `Graph::execute`, or `Graph::execute_on`, the query might be retries for a while.
The logic is that all errors with the `Transient` error class as well as a few other error classes are considered retryable.
This catches errors during a leader election or when the transaction resources on the server (memory, handles, ...) are exhausted.
Retries happen with an exponential backoff until a retry delay exceeds 60s, at which point the query fails.
Transaction created with `Graph::start_txn` or `Graph::start_txn` are *not* retried automatically, only managed transactions are.
> Retry on certain query failures for managed transactions

- lib/src/config.rs
- lib/src/graph.rs
- lib/src/messages.rs
- lib/src/messages/run.rs
- lib/src/query.rs
- lib/src/txn.rs
- lib/tests/container.rs
- lib/tests/txn_change_db.rs
- lib/tests/use_default_db.rs
- **Add option to pass env and server config to testcontainers**
- **Run testcontainers async as all tests are async as well**
- **Only skip EE test when the license was not accepted**
- **Add test to show that the server default db is used**
- **Use server default db over hardcoded default db**
> Use server default db over hardcoded default db

- ci/Cargo.lock.min
- ci/Cargo.lock.msrv
- lib/Cargo.toml
- lib/src/auth/mod.rs
- lib/src/config.rs
- lib/src/connection.rs
- lib/src/pool.rs
This PR adds the possibility of skipping client-side TLS certificate validation.
In the previous version, a user could pass a CA certificate to make an SSC connection work with a self-signed certificate. With this modification, a user can choose to skip the validation completely and avoid passing a valid certificate.
Example of usage:
```
let config = ConfigBuilder::default()
.uri("127.0.0.1:7687")
.user("some_user")
.password("some_password")
.skip_ssl_validation()
.build()
.unwrap();
```
> Add skip_ssl_validation flag and refactor TLS config

- lib/src/messages.rs
- lib/src/messages/ignore.rs
- lib/src/types/serde/de.rs
I noticed the ignore message is only implemented under the unstable bolt implementation feature.
This PR adds support for it in the stable one.
> Add Ignore to current Bolt implementation

- lib/src/bolt/structs/node.rs
- lib/src/packstream/de.rs
- lib/tests/node_property_parsing.rs
Properties are parsed lazily by deserializing the data into an `IgnoredAny`
and then returning the bytes that have been read.
We do parse structs as an enum in order to emit the struct tag as enum tag.
The `IgnoredAny` then deserializes a newtype enum variant, expecting a single item.
The `VariantAccess` impl for the packstream deserializer would then only emit the next field in the struct, introducing the bug.
The fix is to emit all fields when the list of items is from a struct and we are parsing properties.
Fixes #209
> Fix property parsing when a property contains a struct

- ci/Cargo.lock.min
- ci/Cargo.lock.msrv
- lib/Cargo.toml
- lib/src/bolt/request/mod.rs
- lib/src/bolt/request/route.rs
- lib/src/config.rs
- lib/src/connection.rs
- lib/src/errors.rs
- lib/src/graph.rs
- lib/src/lib.rs
- lib/src/messages.rs
- lib/src/messages/run.rs
- lib/src/packstream/ser/mod.rs
- lib/src/pool.rs
- lib/src/query.rs
- lib/src/routing/connection_registry.rs
- lib/src/routing/load_balancing/mod.rs
- lib/src/routing/load_balancing/round_robin_strategy.rs
- lib/src/routing/mod.rs
- lib/src/routing/routed_connection_manager.rs
- lib/src/txn.rs
- lib/src/version.rs
- lib/tests/use_default_db.rs
This PR is a draft implementation of the client-side routing for new4j clusters.
The PR implements the ROUTE message for the unstable version of the protocol (v2).
~- [ ] Bookmarks are not supported at the moment (the array is always sent empty)~
Additional Notes:
- The lock mechanism for refreshing the routing table is sub-optimal (to use an euphemism). We should try to be smarter and use a different method to check for a new routing table.
~- Extra fields in the route message are not implemented yet (part of v4.4)~ Protocol version is now 4.4
- I had to modify the way we serialize some fields: in a structure, the `skip_field` method is now rendering a `null` value
- IMPORTANT: this PR includes a workaround fix to the v2 protocol for date fields deserialization that is crashing the …
> Client side routing implementation

- lib/src/stream.rs
This pull request includes a change to the error handling in the `RowStream` implementation in `lib/src/stream.rs`. The change ensures that the state is set to `Complete(None)` and an `Error::RequestIgnoredError` is returned when the summary is `Ignored`. This because the documentation states:
```
The IGNORED message indicates that the corresponding request has not been carried out.
```
For the RUN command the doc also says:
```
If the server is in a FAILED or INTERRUPTED state, the request will be IGNORED.
```
Error handling improvement:
* [`lib/src/stream.rs`](diffhunk://#diff-5bd844c6f2397bf3b93c5b08057eee21c5cf71899a4c8ce247cd94a4238ec81bL236-R239): Modified the handling of `Summary::Ignored` to set the state to `Complete(None)` and return an `Error::RequestIgnoredError`.
> Handle ignored message as a failure

- lib/src/config.rs
- lib/src/connection.rs
This PR fixes an erroneous behavior of the driver when using a self-signed certificate. The documentation says:
```
The +s variants enable encryption with a full certificate check, and the +ssc variants enable encryption, 
but with no certificate check. This latter variant is designed specifically for use with self-signed certificates.
```
> Always skip ssl validation when using a self-signed certificate

- lib/examples/concurrent_writes.rs
- lib/src/graph.rs
- lib/src/pool.rs
- lib/src/routing/connection_registry.rs
- lib/src/routing/routed_connection_manager.rs
- lib/tests/container.rs
The first connection is done when the first query is run, no need for an async graph creation.
BREAKING CHANGE: The Graph::new and Graph::connect methods are no longer `async`, any `.await` after calling them must be removed.
> Creating a Graph doesn't have to be async

- lib/include/bookmarks.rs
- lib/src/bolt/mod.rs
- lib/src/bolt/request/begin.rs
- lib/src/bolt/request/commit.rs
- lib/src/bolt/request/mod.rs
- lib/src/bolt/request/route.rs
- lib/src/bookmarks.rs
- lib/src/connection.rs
- lib/src/graph.rs
- lib/src/lib.rs
- lib/src/messages.rs
- lib/src/routing/connection_registry.rs
- lib/src/routing/mod.rs
- lib/src/routing/routed_connection_manager.rs
- lib/src/routing/routing_table_provider.rs
- lib/src/summary.rs
- lib/src/txn.rs
- lib/tests/bookmarks.rs
This PR aims to add support for bookmarks in transactions. It also collects bookmarks used in a routed manager and sends them when requesting a new routing table. The list of collected bookmarks is cleared up every time a READ operation returns no bookmarks (that should mean the state of the cluster is consistent).
The bookmarks are sent in the BEGIN message and retrieved from the COMMIT message.
I read somewhere that the command HELLO can also contain bookmarks, but the documentation [does not say a thing about it](https://neo4j.com/docs/bolt/current/bolt/message/#messages-hello).
Bonus: While implementing this feature, I found a problem when getting a connection in a routed environment, caused by a synchronization problem between the manager and the thread fetching the routing table.
* …
> Add bookmarks support

- lib/src/bolt/mod.rs
- lib/src/bolt/request/hello.rs
- lib/src/bolt/request/mod.rs
- lib/src/connection.rs
This PR adds connection hints to the HELLO response. The new object is attached to the connection but not used yet.
> Add connection hints to HELLO response

- lib/src/bolt/request/route.rs
- lib/src/connection.rs
- lib/src/graph.rs
- lib/src/routing/connection_registry.rs
- lib/src/routing/routed_connection_manager.rs
- lib/src/routing/routing_table_provider.rs
- lib/src/types/serde/typ.rs
The goal at the end is to not have to fake-parse the connection string during routing
> Refactor how connections are created

- lib/src/auth/mod.rs
- lib/src/config.rs
- lib/src/connection.rs
Provided mutual authentication support。
```rust
//Used for bidirectional authentication
pub fn with_mutual_tls_validation(
mut self,
client_cert: Option<impl AsRef<Path>>,
ssl_cert: impl AsRef<Path>,
ssl_key: impl AsRef<Path>,
) -> Self {
self.tls_config =
ConnectionTLSConfig::MutualTLS(MutualTLS::new(client_cert, ssl_cert, ssl_key));
self
}
```
https://github.com/neo4j-labs/neo4rs/issues/247
> feat: support MutualTLS.

- .github/workflows/checks.yml
- .github/workflows/create-release-pr.yml
- README.md
- ci/Cargo.lock.min
- ci/Cargo.lock.msrv
- lib/Cargo.toml
- lib/src/bolt/request/route.rs
- lib/src/config.rs
- lib/src/connection.rs
- lib/src/graph.rs
- lib/src/lib.rs
- lib/src/query.rs
- lib/src/routing/connection_registry.rs
- lib/src/routing/load_balancing/mod.rs
- lib/src/routing/load_balancing/round_robin_strategy.rs
- lib/src/routing/mod.rs
- lib/src/routing/routed_connection_manager.rs
- lib/src/routing/routing_table_provider.rs
- lib/src/routing/types.rs
- lib/src/session.rs
- lib/src/txn.rs
- lib/src/utils/concurrent_hashmap.rs
- lib/src/utils/mod.rs
- lib/tests/use_default_db.rs
This PR introduces the concept of sessions when enabling the feature flag unstable-bolt-protocol-impl-v2.
The driver now provides a with_session method, allowing a session to be created on an existing connection. Sessions can be used to specify the target database, impersonate a user, and set the fetch size for queries. Bookmark handling has also been corrected to work properly within sessions.
Additionally, this PR updates the routing logic, as support for user impersonation required changes in that area.
Unfortunately, the changes are many and the PR is quite big.
**Routing Refactor**
Due to a **deadlock** caused by the use of DashMaps in the connection registry, this PR includes a complete refactor of the routing protocol. The router is now lazy and no longer relies on a separate task …
> Introduce session

- lib/src/row.rs
As part of a small feature I'm working on to handle "graphs" as results, I need access to Row keys
> Expose the keys of a Row instance
